//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FurnitureSoftwareUI.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientBasket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientBasket()
        {
            this.OrderProduct = new HashSet<OrderProduct>();
        }
    
        public int id { get; set; }
        public int idClient { get; set; }
        public bool isBuy { get; set; }
        public int idProduct { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProduct> OrderProduct { get; set; }
    }
}
