//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FurnitureSoftwareUI.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderProduct
    {
        public int id { get; set; }
        public int idDiscountClient { get; set; }
        public Nullable<int> Count { get; set; }
        public string Price { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> idOrderList { get; set; }
        public Nullable<int> idBasket { get; set; }
    
        public virtual ClientBasket ClientBasket { get; set; }
        public virtual DiscountClient DiscountClient { get; set; }
    }
}
